spring.application.name=order-service
# If you want to add this service as a producer for multiple kafka streams 
# Then you can just add their url in a comma separated list, like so:
# localhost:9092, localhost:9093, etc
spring.kafka.producer.bootstrap-servers: localhost:9092 

# Now we need to serialize the message via a key-value pair
spring.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.topic.name=order_topics
